version: '3.8'

services:
    issue_db:
      container_name: issue_db
      image: mysql:latest
      restart: always
      environment:
        - MYSQL_DATABASE=yii2basic
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      ports:
        - "3306:3306"
      volumes:
        - ./etc/datebases:/docker-entrypoint-initdb.d
      expose:
        - "3360"
    issue_web:
      image: nginx:1.19-alpine
      container_name: issue_web
      restart: always
      environment:
        - DB_HOST=issue_db
        - DB_NAME=yii2basic
        - DB_USER=yii2
        - DB_PASSWORD=yii2
      ports:
        - "8001:80"
      volumes:
        - ~/.composer-docker/cache:/root/.composer/cache:delegated
        - ./:/app:delegated
        - ./:/var/www
        - ./etc/nginx/conf.d:/etc/nginx/conf.d
    issue_app:
      container_name: issue_app
      build:
        context: ./
        dockerfile: Dockerfile
      restart: unless-stopped
      volumes:
        - ./:/var/www
        - ./etc/php/php.ini:/usr/local/etc/php/php.ini
        - /tmp/xdebug:/tmp/xdebug
      extra_hosts:
        - "host.docker.internal:host-gateway"
      depends_on:
        - issue_db
